repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.5.6" # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
